name: Deploy to Reg.ru

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps
        working-directory: ./app

      - name: Build project
        run: npm run build
        working-directory: ./app

      - name: Archive build files
        run: |
          cd app
          tar -czf ../app.tgz .next public next.config.js package.json package-lock.json

      # Удаляем старый архив на сервере (опционально)
      - name: Remove previous app.tgz on remote
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REG_HOST }}
          username: ${{ secrets.REG_USER }}
          password: ${{ secrets.REG_PASSWORD }}
          port: 22
          script: |
            rm -f /var/www/u3175586/data/www/upak.space/app.tgz

      # Копируем архив на сервер
      - name: Upload to Reg.ru via SFTP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REG_HOST }}
          username: ${{ secrets.REG_USER }}
          password: ${{ secrets.REG_PASSWORD }}
          port: 22
          source: app.tgz
          target: /var/www/u3175586/data/www/upak.space/app.tgz

      # Разархивируем build на сервере
      - name: Extract archive on remote
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REG_HOST }}
          username: ${{ secrets.REG_USER }}
          password: ${{ secrets.REG_PASSWORD }}
          port: 22
          script: |
            cd /var/www/u3175586/data/www/upak.space
            tar -xzf app.tgz
