name: Deploy to Reg.ru

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --no-fund --legacy-peer-deps

      - name: Build project
        run: npm run build

      # --- ДОБАВЛЕН ДИАГНОСТИЧЕСКИЙ ШАГ ---
      - name: Show build result
        run: |
          echo "--- .next ---"
          ls -lR .next || true
          echo "--- public ---"
          ls -lR public || true

      - name: Create deployment archive
        run: |
          mkdir -p deploy
          tar -czf deploy/app.tgz .next public next.config.js package.json package-lock.json

      # --- ЕЩЁ ОДИН ДИАГНОСТИЧЕСКИЙ ШАГ ---
      - name: Check archive content
        run: tar -tzf deploy/app.tgz

      - name: Upload to Reg.ru via SFTP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REG_HOST }}
          username: ${{ secrets.REG_USER }}
          password: ${{ secrets.REG_PASSWORD }}
          port: 22
          source: app/deploy/app.tgz
          target: /var/www/u3175586/data/www/upak.space/  

      - name: Extract archive on remote
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REG_HOST }}
          username: ${{ secrets.REG_USER }}
          password: ${{ secrets.REG_PASSWORD }}
          port: 22
          script: |
            cd /var/www/u3175586/data/www/upak.space
            tar -xzf app.tgz
