name: Deploy Frontend

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      FTP_SERVER: ${{ vars.FTP_SERVER }}
      FTP_PORT: ${{ vars.FTP_PORT }}
      FTP_USERNAME: ${{ vars.FTP_USERNAME }}
      FTP_PASSWORD: ${{ vars.FTP_PASSWORD }}
      FTP_TARGET_DIR: ${{ vars.FTP_TARGET_DIR }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install --no-audit --no-fund
      - run: NEXT_PUBLIC_API_BASE=https://upak.space/ npm run build
      - name: Upload via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ env.FTP_SERVER }}
          port: ${{ env.FTP_PORT }}
          username: ${{ env.FTP_USERNAME }}
          password: ${{ env.FTP_PASSWORD }}
          local_path: ./out
          remote_path: ${{ env.FTP_TARGET_DIR }}
          sftp_only: true
          remove_existing: true
