name: Deploy to Reg.ru

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --no-fund

      - name: Build project
        run: npm run build

      - name: Create deployment archive
        run: |
          mkdir -p deploy
          tar -czf deploy/app.tgz .next public next.config.js package.json package-lock.json

      - name: Upload to Reg.ru via SFTP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REG_HOST }}
          username: ${{ secrets.REG_USER }}
          password: ${{ secrets.REG_PASSWORD }}
          port: 22
          source: deploy/app.tgz
          target: /var/www/upak.space/app.tgz
